# Kansō Pearl for Helix
# Adapted from https://github.com/webhooked/kanso.nvim

inherits = "kanso"

[palette]
# Pearl UI
ui_fg = "#22262D"
ui_fg_dim = "#545464"
ui_bg = "#F2F1EF"
ui_bg_dim = "#E2E1DF"
ui_bg_p1 = "#E2E1DF"
ui_bg_p2 = "#E2E1DF"
ui_special = "#766B90"
ui_nontext = "#A09CAC"
ui_whitespace = "#CACAC7"
ui_indent = "#DDDDDB"
ui_border = "#DDDDDB"
ui_visual = "#DDDDDB"
ui_search = "#B5CBD2"
ui_line_nr = "#9F9F99"
ui_line_nr_active = "#22262D"
ui_cursor_bg = "#22262D"
ui_cursor_fg = "#F2F1EF"
ui_menu_fg = "#43436C"
ui_menu_bg = "#F2F1EF"
ui_menu_selected = "#DDDDDB"
ui_menu_thumb = "#DDDDDB"
ui_float_fg = "#43436C"
ui_float_bg = "#F2F1EF"

# Pearl syntax
syn_string = "#6F894E"
syn_number = "#B35B79"
syn_constant = "#CC6D00"
syn_identifier = "#624C83"
syn_parameter = "#5D57A3"
syn_function = "#4D699B"
syn_keyword = "#624C83"
syn_operator = "#6D6D69"
syn_preproc = "#5C6068"
syn_type = "#597B75"
syn_regex = "#836F4A"
syn_deprecated = "#6D6D69"
syn_punct = "#6D6D69"
syn_comment = "#6D6D69"
syn_special1 = "#836F4A"
syn_special2 = "#624C83"
syn_special3 = "#624C83"

# Pearl diagnostics, version control, and diff backgrounds
diag_error = "#E82424"
diag_ok = "#6F894E"
diag_warning = "#E98A00"
diag_info = "#5A7785"
diag_hint = "#5E857A"
vcs_added = "#6E915F"
vcs_removed = "#D7474B"
vcs_changed = "#DE9800"
diff_add = "#B7D0AE"
diff_delete = "#D9A594"
diff_change = "#D7E3D8"
diff_text = "#F9D791"
