theme = "kanso-ink"

[editor]
line-number = "relative"
cursorline = true
true-color = true
bufferline = "multiple"
mouse = true
end-of-line-diagnostics = "hint"
color-modes = true
auto-format = true
completion-trigger-len = 1
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = true
git-global = true
git-exclude = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.soft-wrap]
enable = false
